server:
  host: "0.0.0.0"
  port: 8080
database:
  driver: postgres
  host: db
  port: 5432
  user : postgres
  #password: supersecret
  name: myapp_db
  migrations_path: /app/deploy
kafka:
  brokers: "kafka:9093"
  topic: "common"
  acks: -1
  linger_ms: 10
  batch_size: 16384